# Generated by Django 5.2.1 on 2025-05-29 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Primary skill name', max_length=255, unique=True)),
                ('lemmatized_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Array of lemmatized variations of the skill', size=None)),
                ('skill_definition', models.TextField(blank=True, help_text='Definition or description of the skill')),
                ('classification', models.CharField(blank=True, help_text='Skill classification/category', max_length=100)),
                ('classification_explanation', models.TextField(blank=True, help_text='Explanation of why this skill belongs to this classification')),
                ('suggested_variations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Array of suggested skill variations', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_name'],
                'indexes': [models.Index(fields=['skill_name'], name='extractor_s_skill_n_627986_idx'), models.Index(fields=['classification'], name='extractor_s_classif_0ac018_idx')],
            },
        ),
    ]
