# Generated by Django 5.2.1 on 2025-05-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_active',
        ),
    ]
