# Generated by Django 4.2.6 on 2025-05-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_add_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Skill name', max_length=255)),
                ('demand', models.CharField(blank=True, help_text='Demand level', max_length=100)),
                ('demand_rationale', models.TextField(blank=True, help_text='Demand explanation')),
                ('risk', models.CharField(blank=True, help_text='Risk level', max_length=100)),
                ('risk_rationale', models.TextField(blank=True, help_text='Risk explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skills_demand',
                'ordering': ['skill'],
                'unique_together': {('skill',)},
            },
        ),
    ]
