# Generated by Django 4.2.6 on 2025-05-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_create_skills_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='extractor_f_name_ce253b_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the file', max_length=255)),
                ('skill_profile', models.JSONField(blank=True, default=dict, help_text='Skill profile data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(help_text='Folder this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='extractor.folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['filename'],
                'indexes': [models.Index(fields=['filename'], name='extractor_f_filenam_19870d_idx'), models.Index(fields=['folder'], name='extractor_f_folder__d8bfac_idx')],
                'unique_together': {('filename', 'folder')},
            },
        ),
    ]
