# Generated by Django 4.2.6 on 2025-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_add_folder_file_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsJobTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Skill name', max_length=500)),
                ('skill_category', models.CharField(help_text='Category of the skill (e.g., Software, Skill, etc.)', max_length=100)),
                ('job_title_1', models.CharField(help_text='Primary job title associated with this skill', max_length=200)),
                ('job_title_2', models.CharField(help_text='Second job title associated with this skill', max_length=200)),
                ('job_title_3', models.CharField(help_text='Third job title associated with this skill', max_length=200)),
                ('job_title_4', models.CharField(help_text='Fourth job title associated with this skill', max_length=200)),
                ('job_title_5', models.CharField(help_text='Fifth job title associated with this skill', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skills Job Title',
                'verbose_name_plural': 'Skills Job Titles',
                'db_table': 'skills_job_titles',
                'ordering': ['skill'],
                'indexes': [models.Index(fields=['skill'], name='skills_job__skill_478a9d_idx'), models.Index(fields=['skill_category'], name='skills_job__skill_c_6473ad_idx'), models.Index(fields=['job_title_1'], name='skills_job__job_tit_301018_idx')],
            },
        ),
    ]
