# Generated by Django 4.2.6 on 2025-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_skillsjobtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillJobFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Skill name', max_length=500)),
                ('skill_type', models.CharField(help_text='Type of skill (e.g., Software, Document, etc.)', max_length=100)),
                ('primary_industry', models.CharField(help_text='Primary industry associated with this skill', max_length=200)),
                ('secondary_industry', models.CharField(blank=True, help_text='Secondary industry associated with this skill', max_length=200)),
                ('primary_job_function', models.CharField(help_text='Primary job function associated with this skill', max_length=200)),
                ('secondary_job_function', models.CharField(blank=True, help_text='Secondary job function associated with this skill', max_length=200)),
                ('related_skill_1', models.CharField(blank=True, help_text='First related skill', max_length=300)),
                ('related_skill_2', models.CharField(blank=True, help_text='Second related skill', max_length=300)),
                ('related_skill_3', models.CharField(blank=True, help_text='Third related skill', max_length=300)),
                ('skill_definition', models.TextField(blank=True, help_text='Definition or description of the skill')),
                ('number', models.IntegerField(blank=True, help_text='Sequential number/ID from the original data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Job Function',
                'verbose_name_plural': 'Skill Job Functions',
                'db_table': 'skill_job_function',
                'ordering': ['skill'],
                'indexes': [models.Index(fields=['skill'], name='skill_job_f_skill_b17b21_idx'), models.Index(fields=['skill_type'], name='skill_job_f_skill_t_c9128e_idx'), models.Index(fields=['primary_industry'], name='skill_job_f_primary_639d04_idx'), models.Index(fields=['primary_job_function'], name='skill_job_f_primary_29b8ea_idx'), models.Index(fields=['number'], name='skill_job_f_number_da7902_idx')],
            },
        ),
    ]
