# Generated by Django 4.2.6 on 2025-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_skilljobfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField(help_text='ID of the primary skill')),
                ('similarity_thresholds', models.JSONField(default=dict, help_text='Dictionary of similarity thresholds and their associated skill IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Similarity',
                'verbose_name_plural': 'Skill Similarities',
                'db_table': 'skill_similarities',
                'ordering': ['skill_id'],
                'indexes': [models.Index(fields=['skill_id'], name='skill_simil_skill_i_dc6ebe_idx')],
                'unique_together': {('skill_id',)},
            },
        ),
    ]
