# Generated by Django 5.2.4 on 2025-07-19 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_skillsimilarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description_filename', models.CharField(max_length=255)),
                ('job_description_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_resumes', models.IntegerField(default=0)),
                ('processed_resumes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'batch_resume_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
                ('match_score', models.FloatField()),
                ('skills_matched', models.IntegerField(default=0)),
                ('total_skills_in_jd', models.IntegerField(default=0)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_details', models.JSONField(blank=True, default=dict)),
                ('batch_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_results', to='extractor.batchresumeanalysis')),
            ],
            options={
                'db_table': 'resume_match_results',
                'ordering': ['-match_score'],
            },
        ),
    ]
